language: java
deploy:
  provider: heroku
  api_key:
    secure: 0fUCtmjYM60locHqM6qjwAXJC/2SP8m4N3SGzgd+Kt61T2o471JmCCyeC5R1Y+W56amSxQAjxxKMcWTpES3gpV9SuK0CE2q5wQapBsUhRL2cwEWDKwHnrI8ZXFqWleYFPqGFnb10oo6rBoetNjQI6tjhWyJEAAnr75HRbvLoLJt3RHudk7br+kCRso7dpzyyqQySQJaLSy8UnVcgHfi11/7KbKaxgqyNH29oXb8Ypvji+87EiaUSCdCAC5UEzVPn6e9uvUwbWgPvasI8CWlEDxnijQlKU/o7a4iJJsPobJvbbRtTEM7orifnDyKoM3x9w6KwFt4hXaP5/qAIrN1i4dTo260VUK/jltGiqurkpr9c3CUpjg6xtVEPrEDuHBcF8MLx0w+obNyyBxMEFt8addp/16tKxazCYG+HdK5+epe8pidZMiwfzDW5jmX+5wLWkO6IH8ieG61uO5rfTmsT4A/XsVOT3w3w0C7QtQZLbF+8RjugKHwTUwlH53z0Wo11Rf5EQHM/67DdINTbh+XNKR0y4D4JS80+Cv6WKI4ZhvADixjl7yTyXAKY/VJktpuJQQysO1ezAQs/GZ7Cney095TDxWCzCdA2aadwKkPajmP1C4oQAN9LxWo/QfIdztnuXaUW6AklSuzCwjnwtOpaozE5/w/iOJ21Ucus7IYV7hQ=
  app: webtictactoe-hugb
  on:
    all_branches: true
